#!/usr/bin/env bash
set -eux
jlpm bootstrap --debug --dev-build=False --minimize=True

echo "maybe cleaning up if on binder..."

if [ "${NB_UID}not-in-docker" = "not-in-docker" ]; then
  echo "...not in docker"
else
  echo "...cleaning up after webpack build"
  rm -rf \
    /srv/conda/envs/notebook/share/jupyterlab/staging \
    ./node_modules/ \
    ./lib/
  jlpm cache clean
fi
