on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PYTHONUNBUFFERED: 1
  PYTHONIOENCODING: utf-8

jobs:
  ci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cache (yarn)
        uses: actions/cache@v1
        with:
          path: .yarn-packages
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-
            yarn-

      - name: install (conda)
        uses: goanpeca/setup-miniconda@v1.6.0
        with:
          environment-file: environment.yml

      - name: build (linux)
        if: ${{ contains(matrix.os, 'ubuntu') }}
        shell: bash -l {0}
        run: |
          source /usr/share/miniconda/bin/deactivate
          source /usr/share/miniconda/bin/activate /usr/share/miniconda/envs/jupyterlab-drawio
          doit all || doit all

      - name: build (macos)
        if: ${{ contains(matrix.os, 'macos') }}
        shell: bash -l {0}
        run: |
          source /usr/local/miniconda/bin/deactivate
          source /usr/local/miniconda/bin/activate /usr/local/miniconda/envs/jupyterlab-drawio
          doit all || doit all

      - name: build (windows)
        if: ${{ contains(matrix.os, 'windows') }}
        shell: cmd /C CALL {0}
        run: |
          call C:\Miniconda\Scripts\deactivate
          call C:\Miniconda\Scripts\activate C:\Miniconda\envs\jupyterlab-drawio
          doit all || doit all
